title: Lilian Marie Boll
profile_img: /assets/img/profile.jpeg
icon_img: /assets/img/icon.webp

name: "Lilian Marie Boll"
job: "PhD Candidate in Bioinformatics"

phone_number: 644-527-015
address: Barcelona, Spain
email: lboll@researchmar.net
linkedin_username: lilian-boll
github_username: justalilibit
twitter_username: _justalilibit
instagram_username: justalilibit
webpage_url: justalilibit.github.io
ORCID_username: 0000-0001-8355-6263
youtube_username: empty
blog_url: justalilibit.github.io

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
